#!/bin/bash

#Set file format
#ts=`date +%s` #Returns seconds
ts=`date +%x.%T` #Returns date and times

#Set working dir
WORKINGDIR=/mnt/Common/Nextcloud/cam/

#Set resolutsion, could be e.g. 640x480 or 1024x768. For more information please check ffmpeg -s.
RESOLUTION=1024x768

#Set your Cam Device path
CAM=/dev/video0

ffmpeg -f video4linux2 -s $RESOLUTION -i $CAM -vframes 3 $WORKINGDIR/vid-$ts.%01d.jpg
exit 0  #important - has to exit with status 0
